# Generated by Django 2.1.7 on 2019-03-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='hello it is a post', max_length=5000),
            preserve_default=False,
        ),
    ]
